Header
training-center/training-center.github.io pull request #12
Opened 2017-05-13 00:59 UTC by baltazarparra

Solicitando PR

2017-05-13 01:00 UTC, khaosdoctor commented
Estou olhando

2017-05-13 01:50 UTC, khaosdoctor approved these changes

2017-05-13 01:52 UTC, woliveiras commented
Já vai corrigir o conflito, @khaosdoctor?

2017-05-13 01:53 UTC, khaosdoctor requested changes
@baltazarparra eu não consigo mesclar por causa do conflito D: vc tem que resolver ele ai do seu lado e mandar o commit :S

Ele não deixa eu resolver por aqui

2017-05-13 02:00 UTC, merged

2017-05-14 03:37 UTC, khaosdoctor commented
Corrigido aqui, nem precisei dar o merge pelo github :D