Alterações no header responsivo
training-center/training-center.github.io pull request #17
Opened 2017-05-16 18:18 UTC by YuriBrunetto

Apenas alguns ajustes para não quebrar quando o site estiver no mobile. 

Os ícones com `flexbox` foi uma ideia apenas, desse jeito eles se alinham certinho.

2017-05-16 18:49 UTC, anony000 commented
Você usou o conceito de mobile-first?

2017-05-16 18:50 UTC, YuriBrunetto commented
@anony000 isso

2017-05-16 18:53 UTC, anony000 commented
Tem como colocar um espaçamento nas bordas para ficar mais fiel ao [layout original](http://i.imgur.com/l9BRFtU.png)

2017-05-16 18:54 UTC, YuriBrunetto commented
@anony000 verdade, removi os padding laterais sem querer! já arrumo

2017-05-16 18:56 UTC, anony000 commented
Tranquilo man!

2017-05-16 19:10 UTC, anony000 commented
Também concordo sobre o uso do mobile-first, só não usei por que na live os caras falaram que ia fazer depois e que não era legal,etc, dai deixei quieto.

2017-05-17 00:26 UTC, khaosdoctor requested changes
Algumas sugestões que _eu_ acho que ficariam legais:

![image](https://cloud.githubusercontent.com/assets/3200560/26133496/dc013cc2-3a7d-11e7-93ab-9af1285b8597.png)

A gente poderia dar um espaço de 25px mais ou menos entre o título e a descrição com `.titulo { margin-bottom: 25px; }` ou alguma outra coisa mais semântica.

No botão a mesma coisa, colocar um top de 20px só pra ele ficar mais longe do texto.

__Probleminhas__

1. No modo paisagem ele fica meio quebrado
![image](https://cloud.githubusercontent.com/assets/3200560/26133530/18cec124-3a7e-11e7-8515-f397438a03d8.png)

Acho que o ideal é fazer o texto de descrição por baixo do título em duas linhas full size aqui

2. No iPad mini em modo retrato ele fica muito colado também

![image](https://cloud.githubusercontent.com/assets/3200560/26133547/38e84d9a-3a7e-11e7-9092-a970067e69a8.png)

Acho que é a mesma situação do anterior, fora isso está tudo bem com os outros icones e etc 😄

2017-05-17 04:40 UTC, YuriBrunetto commented
@khaosdoctor gostei das tuas ideias, apliquei elas no commit!

Um jeito que achei para resolver os paddings foi adicionar mais breakpoints e trocar o `flex-direction` para quando tivermos uma largura de tela maior.

2017-05-17 04:58 UTC, anony000 commented
Man, não seria melhor colocar os `@media-queries` no final do código, tipo fica algo mais organizado, e será que é uma boa prática ir aplicando vários breakpoint assim, aleatórios? Não estou dizendo para usar o grid do bootstrap, porém usa os breakpoints dele como referência. Assim:

```
@media (max-width: 768px) { ... }
@media (min-width: 768px) and (max-width: 992px) { ... }
@media (min-width: 992px) and (max-width: 1200px) { ... }
@media (min-width: 1200px) { ... }
```

2017-05-17 05:02 UTC, YuriBrunetto commented
@anony000 na minha opinião, acho que fica mais organizado colocar os media-queries abaixo dos elementos em que vamos mudar... Acho que fica bem melhor de achar.

Sobre os breakpoints aleatórios: pra mim tanto faz, eu usei esses números que fazem parte de uma grid que sempre usei. Mas, podemos definir os breakpoints do projeto! 😄

2017-05-17 05:05 UTC, anony000 commented
Certamente hehe, teria os breakpoints do seus grid aí? Tem como compartilhar?

2017-05-17 05:08 UTC, YuriBrunetto commented
Grid beeem antiga... Se não me engano, era:
`320px, 480px, 640px, 880px, 960px, 1280px`

2017-05-17 11:51 UTC, woliveiras commented
Parabéns, galera!

Vocês estão detonando!

2017-05-17 13:18 UTC, khaosdoctor commented
@YuriBrunetto @anony000 Ai eu acho que vale criar outro arquivo `heade.mobile.css` só com os media queries

2017-05-17 13:19 UTC, khaosdoctor approved these changes
Só uma sugestão de mudar em outro arquivo os medias, mas de código eu acho que está perfeito

2017-05-17 13:19 UTC, khaosdoctor commented on styles.css
> +@media (min-width: 640px) {
Isso é só pra reforçar o que eu tinha falado na PR, mas não é melhor criar outro arquivo com os mobiles?

2017-05-17 16:31 UTC, adeonir commented
Mais adiante, quando usar um preprocessador, aí acho válido usar um css para o mobile, pois daí faz um concact e já era. Com CSS puro, vai gerar mais um request no servidor.

2017-05-17 17:48 UTC, khaosdoctor commented
@adeonir Tem razão, vamos manter assim

2017-05-17 17:48 UTC, merged

2017-05-17 17:48 UTC, khaosdoctor commented
Mesclado 😄

2017-05-17 18:40 UTC, YuriBrunetto commented
Dalhe! 😄