Improvement in home texts
training-center/training-center.github.io pull request #40
Opened 2018-03-28 01:19 UTC by morais90

Fix some concordance mistakes and improve phrases interpretation.

2018-03-28 09:07 UTC, woliveiras commented on index.html
> +				Esse projeto, sem fins lucrativos, tem o objetivo
Rapaz, desse modo ficou um texto muito coeso, porém o objetivo ali é ser um texto de marketing... Não se usa tanta formalidade... Por isso inicia com `Um projeto...`, pois `Esse projeto, sem fins lucrativos` fica muito formal.

2018-03-28 09:07 UTC, woliveiras commented on index.html
> +				Independente do seu nível profissional, você é
Essa parte ficou linda! \o/ <3

2018-03-28 09:07 UTC, woliveiras commented on index.html
> +				Essa iniciativa surgiu para juntar membros das
Aqui também ficou show!

2018-03-28 09:07 UTC, woliveiras commented on index.html
> +				Você pode organizar um grupo de estudos sobre
Acha que seria legal colocarmos `nós` ao invés de `você` para nos aproximarmos mais do leitor?

2018-03-28 09:07 UTC, woliveiras commented on index.html
> +				Se pintar alguma oportunidade como freelancer,
Show de bola!

2018-03-28 09:07 UTC, woliveiras commented on index.html
> +				O projeto Mentoria tem por objetivo unir as
Muito bom!

2018-03-28 09:07 UTC, woliveiras commented on index.html
> +				Sabemos que o início pode ser cruel e
Muito bom!

2018-03-28 09:07 UTC, woliveiras commented on index.html
> +				que queremos ajudar alguém. Por isso, por favor, tenha
Aqui também ficou show!

2018-03-28 09:08 UTC, woliveiras commented
Muito obrigado pela contribuição, @morais90!

Fiz alguns comentários para avaliarmos. Somente o primeiro texto que não curti muito, pois ficou parecendo meio formal, mas de resto achei perfeito! :metal:

2018-03-29 17:46 UTC, khaosdoctor requested changes
Acho que só revisar a primeira parte do texto, ao invés de `Esse projeto` trocar por `Um projeto` ficaria show, o resto está muito bom :)

2018-03-29 17:46 UTC, khaosdoctor commented on index.html
> +				Você pode organizar um grupo de estudos sobre
Acho que dá pra deixar o `você` hein, porque remete que o próprio visitante é responsável e pode fazer o que ele precisar

2018-03-29 17:46 UTC, khaosdoctor commented on index.html
> +				Esse projeto, sem fins lucrativos, tem o objetivo
Concordo nessa parte

2018-05-07 13:18 UTC, woliveiras commented
O site foi alterado. Seria necessário um outro PR e uma nova revisão, galera.

Se possível, faça essa revisão no nosso conteúdo, @morais90 

Vou subir uma nova versão hoje, recomendo que faça isso amanhã ou depois do novo commit.

2018-05-07 13:18 UTC, closed without merging